Apps/Zs.App.Home/Zs.App.Home.Web/Areas/Admin/Controllers/ServerInfoController.cs
using Microsoft.AspNetCore.Mvc;
using Zs.App.Home.Web.Areas.Admin.Models.ServerInfo;

namespace Zs.App.Home.Web.Areas.Admin.Controllers
{

    /// <summary>
    /// Shows general server status(errors, memory usage, etc.)
    /// </summary>
    [Area("admin")]
    [Route("admin/[controller]")] // Нужен для AJAX
    public class ServerInfoController : Controller
    {
        private readonly Server _serverInfo = new Server();

        //[Route("")]
        //[Route("index")]
        ////[Route("admin/ServerInfo/index")]
        //[Route("~/")]
        public IActionResult Index()
        {
            return View(_serverInfo);
        }

        //[HttpPost]
        [Route("AjaxUpdateCommonInfo")]
        public IActionResult AjaxUpdateCommonInfo()
        {
            return PartialView("_EnvironmentInfo", _serverInfo.EnvironmentInfo);
        }
    }
}

Apps/Zs.App.Home/Zs.App.Home.Web/Areas/Admin/Controllers/VisitorInfoController.cs
using Microsoft.AspNetCore.Mvc;
using Zs.App.Home.Web.Areas.Admin.Models.VisitorInfo;

namespace Zs.App.Home.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// Shows information about visitor
    /// </summary>
    [Area("admin")]
    public class VisitorInfoController : Controller
    {
        public IActionResult Index()
        {
            var visitor = new Visitor(HttpContext);

            return View(visitor);
        }
    }
}

Apps/Zs.App.Home/Zs.App.Home.Web/Areas/ApiVk/Controllers/ActivityLogController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Zs.App.Home.Services.Vk;

namespace Zs.App.Home.Web.Areas.ApiVk.Controllers
{
    [Area("apivk")]
    [Route("apivk/[controller]")] // необходим для формирования полного маршрута при использовании короткого маршрута в HttpGet
    public class ActivityLogController : Controller
    {
        private readonly IActivityService _vkActivityService;
        //private readonly IZsLogger _logger;

        public ActivityLogController(IActivityService vkActivityService)
        {
            _vkActivityService = vkActivityService ?? throw new ArgumentNullException(nameof(vkActivityService));
        }

        [HttpGet("test", Name = "Test1")]
        public IActionResult Test(ushort page = 1)
        {
            try
            {
                return Ok("Test");
            }
            catch (Exception ex)
            {
                return Ok(new
                {
                    InnerExceptionMessage = ex.InnerException?.Message,
                    InnerExceptionType = ex.InnerException?.GetType().FullName,
                    InnerExceptionStackTrace = ex.InnerException?.StackTrace,
                    Message = ex.Message,
                    Type = ex.GetType().FullName,
                    StackTrace = ex.StackTrace
                });
                //return StatusCode(500);
            }
        }

        [HttpGet("all/{page?}", Name = "GetLastActivityPage")]
        public async Task<IActionResult> Get(ushort page = 1)
        {
            try
            {
                var result = await _vkActivityService.GetLastActivity(page);
                return Ok(result);
            }
            catch (Exception ex)
            {
                //_logger.LogError(ex, nameof(ActivityLogController));
                return Ok(new {
                    InnerExceptionMessage = ex.InnerException?.Message,
                    InnerExceptionType = ex.InnerException?.GetType().FullName,
                    InnerExceptionStackTrace = ex.InnerException?.StackTrace,
                    Message = ex.Message,
                    Type = ex.GetType().FullName,
                    StackTrace = ex.StackTrace
                });
                //return StatusCode(500);
            }
        }


        [HttpGet("User/{id?}", Name = "GetUserActivity")]
        public async Task<IActionResult> Get(int id = 0)
        {
            try
            {
                var fromDate = DateTime.Today - TimeSpan.FromDays(2);
                var toDate = DateTime.Today - TimeSpan.FromDays(1);

                var result = await _vkActivityService.GetUserStatistics(id, fromDate, toDate);
                return Ok(result);
            }
            catch (Exception ex)
            {
                //_logger.LogError(ex, nameof(ActivityLogController));
                return Ok(new
                {
                    InnerExceptionMessage = ex.InnerException?.Message,
                    InnerExceptionType = ex.InnerException?.GetType().FullName,
                    InnerExceptionStackTrace = ex.InnerException?.StackTrace,
                    Message = ex.Message,
                    Type = ex.GetType().FullName,
                    StackTrace = ex.StackTrace
                });
                //return StatusCode(500);
            }
        }

        //// POST api/<ActivityLogController>
        //[HttpPost]
        //public void Post([FromBody] string value)
        //{
        //}
        //
        //// PUT api/<ActivityLogController>/5
        //[HttpPut("{id}")]
        //public void Put(int id, [FromBody] string value)
        //{
        //}
        //
        //// DELETE api/<ActivityLogController>/5
        //[HttpDelete("{id}")]
        //public void Delete(int id)
        //{
        //}
    }
}

Apps/Zs.App.Home/Zs.App.Home.Web/Areas/App/Controllers/VkController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;
using Zs.App.Home.Services.Vk;
using Zs.App.Home.Web.Areas.App.Models.Vk;
using Zs.App.Home.Web.Areas.App.Services;

namespace Zs.App.Home.Web.Areas.App.Controllers
{
    [Area("app")]
    [Route("app/[controller]")]
    public class VkController : Controller
    {
        private readonly IActivityService _service;
        private readonly ILogger<VkController> _logger;
        private readonly VkMapper _mapper = new VkMapper();

        public VkController(IActivityService service, ILogger<VkController> logger)
        {
            _service = service ?? throw new ArgumentNullException(nameof(service));
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new VkVM());
        }

        [HttpGet]
        [Route("AjaxAddNewVkUser")]
        public Task<IActionResult> AjaxAddNewVkUser(int id)
        {
            throw new NotImplementedException();
            //var result = await _service.AddNewVkUser(id);
            //return result.IsSuccess ? Ok(_mapper.ToNewVkUserResult(result)) : StatusCode(500);
        }

        [HttpGet]
        [Route("AjaxGetUsers")]
        public async Task<IActionResult> AjaxGetUsers(string filterText)
        {
            var result = await _service.GetVkUsers(filterText);
            // TODO: handle error
            return PartialView("_Users", _mapper.ToUsersVM(result));
        }

        [HttpGet]
        [Route("AjaxGetUsersWithActivity")]
        public async Task<IActionResult> AjaxGetUsersWithActivity(string filterText, DateTime fromDate, DateTime toDate)
        {
            //_logger.LogInformation("AjaxGetUsersWithActivity");

            var result = await _service.GetVkUsersWithActivity(filterText, fromDate, toDate);
            return PartialView("_Users", _mapper.ToUsersVMWithActivity(result));
        }

        [HttpGet]
        [Route("AjaxGetUserActivity")]
        public async Task<IActionResult> AjaxGetUserActivity(int userId, DateTime fromDate, DateTime toDate)
        {
            if (userId == 0)
                return null;
            var result = await _service.GetUserActivity(userId, fromDate, toDate);
            // TODO: handle error
            return PartialView("_UserActivity", _mapper.ToPeriodUserActivityVM(result));
        }

        [HttpGet]
        [Route("AjaxGetDetailedUserActivity")]
        public async Task<IActionResult> AjaxGetDetailedUserActivity(int userId)
        {
            var result = await _service.GetDetailedUserActivity(userId);
            // TODO: handle error
            return PartialView("_DetailedUserActivity", _mapper.ToDetailedUserActivityVM(result));
        }
    }
}

Apps/Zs.App.Home/Zs.App.Home.Web/Views/Shared/_JsonPanel.cshtml
@model string

<textarea style="width:100%; height:100%;">
    @Model
</textarea>

Apps/Zs.App.Home/Zs.App.Home.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - zuev56's home website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Common.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Zuev56</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="ServerInfo" asp-action="Index">Server</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="ServicesInfo" asp-action="Index">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="VisitorInfo" asp-action="Index">Visitor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="app" asp-controller="Vk" asp-action="Index">Vk Info</a>
                        </li>
                        <li class="nav-item">
                            @*<a class="nav-link text-dark" asp-area="apivk" asp-controller="ActivityLog" asp-action="Get">API Vk</a>*@
                            @*<a class="nav-link text-dark" asp-area="apivk" asp-route="/ActivityLog/test">API Vk</a>*@
                            <a class="nav-link text-dark" href="@Url.RouteUrl("GetLastActivityPage")">API Vk</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Zuev56 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>